# Generated by Django 4.1.3 on 2023-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField(default=0)),
                ('id_vara', models.IntegerField(default=0)),
                ('id_juiz', models.IntegerField(default=0)),
                ('id_aux_jus', models.IntegerField(default=0)),
                ('data_nomeacao', models.DateTimeField(verbose_name='data da nomeação')),
                ('honorarios', models.IntegerField(default=0)),
                ('data_intimacao', models.DateTimeField(verbose_name='data da intimação')),
                ('data_aceite', models.DateTimeField(verbose_name='data da petição de aceite')),
                ('assunto', models.CharField(max_length=300)),
                ('requerente', models.CharField(max_length=300)),
                ('requerido', models.CharField(max_length=300)),
                ('data_inicio_pericia', models.DateTimeField(verbose_name='data inicio da pericia')),
                ('data_final_pericia', models.DateTimeField(verbose_name='data final da pericia')),
                ('data_laudo_protocolado', models.DateTimeField(verbose_name='data do laudo protocolado')),
            ],
        ),
    ]
