# Generated by Django 4.1.3 on 2023-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar_justica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aux_jus', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(verbose_name='data do cadastro do perito')),
                ('cpf', models.IntegerField(default=0)),
                ('tel', models.IntegerField(default=0)),
                ('cel', models.IntegerField(default=0)),
                ('email1', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=200)),
            ],
        ),
    ]
