# Generated by Django 4.1.3 on 2023-04-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auxiliar_justica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juiz', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=200)),
                ('id_vara', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vara', models.IntegerField(default=0)),
                ('endereco', models.CharField(max_length=200)),
                ('tel', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
